### ISSUE TITLE
Error in wordclouds

### ISSUE THREAD

**Issue by gorkang** [mkearney/rstudioconf_tweets#2]
When sourcing words.R there is an error. In my case, it was solved by adding:

```
if (!requireNamespace("bpa", quietly = TRUE)) {
  install.packages("bpa")}

```

**Comment by mkearney** [comment]
Good catch. It was actually due to the function `trim_ws` from [tfse](https://github.com/mkearney/tfse) (my personal utility package). I've replaced that function with the equivalent code. I'm sure the {bpa} package is perfectly fine, but I don't want to cause people to install packages they don't need too :).
